### ISSUE TITLE
作者是否可以破解进入图书馆的闸机接口

### ISSUE THREAD

**Issue by ydteng** [DefJia/Auto_Reservation_System_BE#10]
别的接口都可以通过抓包实现，但是进入图书馆没办法抓包，也很难猜出接口的url

**Comment by DefJia** [comment]
emmm目前看来这个比较难做到。
P.S. 这只是一个用来辅助预约的工具哈，最好不要用这个来霸占座位，还是要正常签到签离的呀 :-)
