### ISSUE TITLE
Raspberry Pi 安装pyaudio失败

### ISSUE THREAD

**Issue by LoveCatc** [DefJia/Auto_Reservation_System_BE#9]
使用debian pi aarch64系统，直接pip安装依赖时会提示pyaudio安装失败。
具体问题是
```bash
src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or directory
     #include "portaudio.h"
``` 
为了解决问题，需要首先安装依赖
`sudo apt-get install portaudio19-dev python-all-dev python3-all-dev`
然后再安装就不会出现问题。

**Comment by DefJia** [comment]
感谢py！我有空加到文档里呀！ :beers: :beers:
